version: '3.8'

services:
  proxy:
    image: dixon961/easy-proxy:latest
    build:
      context: .
    container_name: vless-proxy
    environment:
      # provide one of the *_LINK env
      X_UI_LINK: ""
      # PresharedKey is optional
      WIREGUARD_LINK: |
        [Interface]
        PrivateKey = 
        Address = 10.0.0.2/32
        DNS = 1.1.1.1, 1.0.0.1
        MTU = 1420

        # dixon-wireguard-1
        [Peer]
        PublicKey = 
        AllowedIPs = 0.0.0.0/0, ::/0
        Endpoint = 
        PresharedKey = 
      PROXY_USER: "" # optional
      PROXY_PASS: "" # optional
    ports:
      - "1080:1080"   # SOCKS5
      - "3128:3128"   # HTTP
    extra_hosts:
      - "host.docker.internal:host-gateway"
