version: '3.8'

services:
  proxy:
    image: dixon961/easy-proxy:latest
    build:
      context: .
    container_name: vless-proxy
    environment:
      X_UI_LINK: ""
      PROXY_USER: "" # optional
      PROXY_PASS: "" # optional
    ports:
      - "1080:1080"   # SOCKS5
      - "3128:3128"   # HTTP
    extra_hosts:
      - "host.docker.internal:host-gateway"
